# generated by datamodel-codegen:
#   filename:  bets.json
#   timestamp: 2025-02-16T19:07:35+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel, confloat


class UserUsernameBets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    username: str
    limit: Optional[confloat(ge=0.0, le=1000.0)] = 1000


class Model(RootModel[UserUsernameBets]):
    root: UserUsernameBets
