# generated by datamodel-codegen:
#   filename:  {id}.json
#   timestamp: 2025-02-16T19:07:35+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, RootModel


class MarketId(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    lite: Optional[Union[bool, str]] = None


class Model(RootModel[MarketId]):
    root: MarketId
