# generated by datamodel-codegen:
#   filename:  {slug}.json
#   timestamp: 2025-02-16T19:07:34+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class GroupSlug(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str


class Model(RootModel[GroupSlug]):
    root: GroupSlug
