# generated by datamodel-codegen:
#   filename:  {username}.json
#   timestamp: 2025-02-16T19:07:34+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class UserUsername(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    username: str


class Model(RootModel[UserUsername]):
    root: UserUsername
