# generated by datamodel-codegen:
#   filename:  markets.json
#   timestamp: 2025-02-16T19:07:34+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel, confloat


class GroupByIdIdMarkets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    limit: Optional[confloat(ge=0.0, le=1000.0)] = 500


class Model(RootModel[GroupByIdIdMarkets]):
    root: GroupByIdIdMarkets
