# generated by datamodel-codegen:
#   filename:  {slug}.json
#   timestamp: 2025-02-16T19:07:33+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, RootModel


class SlugSlug(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: str
    lite: Optional[Union[bool, str]] = None


class Model(RootModel[SlugSlug]):
    root: SlugSlug
