# generated by datamodel-codegen:
#   filename:  {id}.json
#   timestamp: 2025-02-16T19:07:34+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class GroupByIdId(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str


class Model(RootModel[GroupByIdId]):
    root: GroupByIdId
