# generated by datamodel-codegen:
#   filename:  comments.json
#   timestamp: 2025-02-16T19:07:30+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, RootModel, confloat


class Comments(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractId: Optional[str] = None
    contractSlug: Optional[str] = None
    limit: Optional[confloat(ge=0.0, le=1000.0)] = 1000
    page: Optional[confloat(ge=0.0)] = 0
    userId: Optional[str] = None
    isPolitics: Optional[Union[bool, str]] = None


class Model(RootModel[Comments]):
    root: Comments
