# generated by datamodel-codegen:
#   filename:  get-compatibility-questions.json
#   timestamp: 2025-02-16T19:07:30+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class GetCompatibilityQuestions(BaseModel):
    pass
    model_config = ConfigDict(
        extra="forbid",
    )


class Model(RootModel[GetCompatibilityQuestions]):
    root: GetCompatibilityQuestions
