# generated by datamodel-codegen:
#   filename:  groups.json
#   timestamp: 2025-02-16T19:07:32+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel, confloat


class Groups(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    availableToUserId: Optional[str] = None
    beforeTime: Optional[int] = None
    limit: Optional[confloat(ge=0.0, le=1000.0)] = 500


class Model(RootModel[Groups]):
    root: Groups
