# generated by datamodel-codegen:
#   filename:  leagues.json
#   timestamp: 2025-02-16T19:07:32+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class Leagues(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    userId: Optional[str] = None
    cohort: Optional[str] = None
    season: Optional[float] = None


class Model(RootModel[Leagues]):
    root: Leagues
