# generated by datamodel-codegen:
#   filename:  managram.json
#   timestamp: 2025-02-16T19:07:30+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, RootModel, constr


class Token(Enum):
    M_ = "M$"
    CASH = "CASH"


class Managram(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount: float
    toIds: List[str]
    message: constr(max_length=10000)
    groupId: Optional[constr(max_length=60)] = None
    token: Optional[Token] = "M$"


class Model(RootModel[Managram]):
    root: Managram
