# generated by datamodel-codegen:
#   filename:  managrams.json
#   timestamp: 2025-02-16T19:07:31+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel, confloat


class Managrams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    toId: Optional[str] = None
    fromId: Optional[str] = None
    limit: Optional[confloat(ge=0.0, le=100.0)] = 100
    before: Optional[float] = None
    after: Optional[float] = None


class Model(RootModel[Managrams]):
    root: Managrams
