# generated by datamodel-codegen:
#   filename:  me.json
#   timestamp: 2025-02-16T19:07:32+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class Me(BaseModel):
    pass
    model_config = ConfigDict(
        extra="forbid",
    )


class Model(RootModel[Me]):
    root: Me
