# generated by datamodel-codegen:
#   filename:  txns.json
#   timestamp: 2025-02-16T19:07:33+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, RootModel, confloat


class Txns(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: Optional[str] = None
    offset: Optional[float] = 0
    limit: Optional[confloat(ge=0.0, le=100.0)] = 100
    before: Optional[float] = None
    after: Optional[float] = None
    toId: Optional[str] = None
    fromId: Optional[str] = None
    category: Optional[str] = None
    ignoreCategories: Optional[List[str]] = None


class Model(RootModel[Txns]):
    root: Txns
