# generated by datamodel-codegen:
#   filename:  add-bounty.json
#   timestamp: 2025-02-16T19:07:37+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, PositiveFloat, RootModel


class MarketContractIdAddBounty(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractId: str
    amount: PositiveFloat


class Model(RootModel[MarketContractIdAddBounty]):
    root: MarketContractIdAddBounty
