# generated by datamodel-codegen:
#   filename:  answer.json
#   timestamp: 2025-02-16T19:07:38+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel, constr


class MarketContractIdAnswer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractId: constr(max_length=240)
    text: constr(min_length=1, max_length=240)


class Model(RootModel[MarketContractIdAnswer]):
    root: MarketContractIdAnswer
