# generated by datamodel-codegen:
#   filename:  award-bounty.json
#   timestamp: 2025-02-16T19:07:36+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, PositiveFloat, RootModel


class MarketContractIdAwardBounty(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractId: str
    commentId: str
    amount: PositiveFloat


class Model(RootModel[MarketContractIdAwardBounty]):
    root: MarketContractIdAwardBounty
