# generated by datamodel-codegen:
#   filename:  close.json
#   timestamp: 2025-02-16T19:07:36+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel, conint


class MarketContractIdClose(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractId: str
    closeTime: Optional[conint(ge=0)] = None


class Model(RootModel[MarketContractIdClose]):
    root: MarketContractIdClose
