# generated by datamodel-codegen:
#   filename:  group.json
#   timestamp: 2025-02-16T19:07:37+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class MarketContractIdGroup(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractId: str
    groupId: str
    remove: Optional[bool] = False


class Model(RootModel[MarketContractIdGroup]):
    root: MarketContractIdGroup
