# generated by datamodel-codegen:
#   filename:  sell.json
#   timestamp: 2025-02-16T19:07:37+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, PositiveFloat, RootModel


class Outcome(Enum):
    YES = "YES"
    NO = "NO"


class MarketContractIdSell(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    contractId: str
    shares: Optional[PositiveFloat] = None
    outcome: Outcome
    answerId: Optional[str] = None
    deterministic: Optional[bool] = None
    deps: Optional[List[str]] = None


class Model(RootModel[MarketContractIdSell]):
    root: MarketContractIdSell
